package io.bluetape4k.leader.examples.dynamodbexport

import io.bluetape4k.codec.Base58
import io.bluetape4k.leader.dynamodb.DynamoDbLeaderElectionOptions
import io.bluetape4k.leader.dynamodb.DynamoDbSuspendLeaderElector
import io.bluetape4k.logging.KLogging
import io.bluetape4k.logging.info
import io.bluetape4k.testcontainers.aws.DynamoDbLocalServer
import kotlin.time.Duration.Companion.milliseconds
import kotlin.time.Duration.Companion.seconds
import kotlinx.coroutines.CompletableDeferred
import kotlinx.coroutines.async
import kotlinx.coroutines.runBlocking
import software.amazon.awssdk.auth.credentials.AwsBasicCredentials
import software.amazon.awssdk.auth.credentials.StaticCredentialsProvider
import software.amazon.awssdk.regions.Region
import software.amazon.awssdk.services.dynamodb.DynamoDbAsyncClient
import software.amazon.awssdk.services.dynamodb.DynamoDbClient

/**
 * Demonstrates leader-only scheduled exports using DynamoDB Local.
 */
object DynamoDbExportDemo: KLogging() {

    @JvmStatic
    fun main(args: Array<String>) = runBlocking {
        val container = DynamoDbLocalServer.Launcher.dynamoDb
        val credentials = StaticCredentialsProvider.create(
            AwsBasicCredentials.create(container.awsAccessKey, container.awsSecretKey),
        )
        val region = Region.of(container.regionName)
        val syncClient = DynamoDbClient.builder()
            .endpointOverride(container.awsEndpoint)
            .credentialsProvider(credentials)
            .region(region)
            .build()
        val asyncClient = DynamoDbAsyncClient.builder()
            .endpointOverride(container.awsEndpoint)
            .credentialsProvider(credentials)
            .region(region)
            .build()

        try {
            val suffix = Base58.randomString(8)
            val lockTableName = "leader_export_locks_$suffix"
            val exportTableName = "leader_exports_$suffix"
            DynamoDbExportTable.createLockTable(syncClient, lockTableName)
            DynamoDbExportTable.createExportTable(syncClient, exportTableName)
            val exportTable = DynamoDbExportTable(syncClient, exportTableName)

            val lockName = "billing-export"
            val keyPrefix = "examples-dynamodb-export-$suffix"
            val nodeA = newRunner("node-a", lockName, lockTableName, keyPrefix, asyncClient, exportTable)
            val nodeB = newRunner("node-b", lockName, lockTableName, keyPrefix, asyncClient, exportTable)
            val leaderStarted = CompletableDeferred<Unit>()
            val releaseLeader = CompletableDeferred<Unit>()

            log.info { "=== DynamoDB scheduled export demo start ===" }

            val firstBatch = async {
                nodeA.runOnce("billing-2026-06-05") {
                    leaderStarted.complete(Unit)
                    releaseLeader.await()
                    "billing export generated by node-a"
                }
            }

            leaderStarted.await()
            val skipped = nodeB.runOnce("billing-2026-06-05") {
                error("node-b must skip while node-a holds the export lock")
            }

            releaseLeader.complete(Unit)
            val exported = firstBatch.await()
            val nextBatch = nodeB.runOnce("billing-2026-06-06") {
                "billing export generated by node-b after release"
            }

            log.info { "exported=$exported" }
            log.info { "skipped=$skipped" }
            log.info { "nextBatch=$nextBatch" }
            log.info { "records=${exportTable.records()}" }
            log.info { "=== DynamoDB scheduled export demo complete ===" }
        } finally {
            asyncClient.close()
            syncClient.close()
        }
    }

    private fun newRunner(
        nodeId: String,
        lockName: String,
        lockTableName: String,
        keyPrefix: String,
        asyncClient: DynamoDbAsyncClient,
        exportTable: DynamoDbExportTable,
    ): DynamoDbScheduledExportRunner {
        val options = DynamoDbExportRunnerOptions(
            nodeId = nodeId,
            lockName = lockName,
        )
        val elector = DynamoDbSuspendLeaderElector(
            asyncClient,
            DynamoDbLeaderElectionOptions(
                leaderOptions = options.leaderOptions,
                tableName = lockTableName,
                keyPrefix = keyPrefix,
                clockSkewTolerance = 10.milliseconds,
                ttlPadding = 1.seconds,
            ),
        )
        return DynamoDbScheduledExportRunner(options, elector, exportTable)
    }
}
