package io.bluetape4k.leader.identity

/**
 * Provenance of a resolved leader ID — used as a Micrometer tag value.
 *
 * ## Contract
 * Exactly 4 values. Bounded cardinality is required for Micrometer tag safety.
 * AUTO source generates a unique ID per call and may cause LRU churn in [LeaderElectorBridgeLog].
 */
enum class LeaderIdSource {
    /** Statically specified literal string in the annotation `leaderId` field. */
    LITERAL,
    /** Resolved from a Spring SpEL expression in the annotation `leaderId` field. */
    SPEL,
    /** Resolved from a Spring `${...}` property placeholder. */
    PROPERTY,
    /** Auto-generated by the configured [LeaderIdProvider] bean (default: [RandomLeaderIdProvider]). */
    AUTO,
}
